### PR TITLE
Fixed OS Parsing for v3 replacement

### PR DESCRIPTION
**Pull request by nikunjb**
3 OS Parsing tests were failing. This was due to v3 replacement not occurring in OSParser. Fixed with this commit.

### CODE REVIEW

**Comment by mmarmol** [comment]
Hey @nikunjb   I am currently working in a project that is bases on this lib but I am trying to put things up to date. For example I have a remote url load for the yaml and a scheduled load. I added this changes also. I would love to hear feedback from you.

**Comment by nikunjb** [comment]
Good to hear Marcelo. Yeah, I was trying to use this library also for our
own purposes. However, it seems like its not being actively maintained and
there was this issue of OS Parsing not working correctly anymore in the
java code with the new Regular expressions in the uap-core project. Hence I
had to make this patch. Hope its working for you.

Thanks
Nikunj

**Comment by mmarmol** [comment]
@nikunjb Yeah, same here basically. I am trying to keep it up date. If you have a case I can test where the parsing is not working right now please let me know I would like to fix that.
You can check progress here:
https://github.com/mmarmol/uap-java

**Comment by mmarmol** [comment]
That is a really useful feedback. Will look into it today. Thanks!

**Comment by mmarmol** [comment]
@nikunjb  The test are passing, regarding the Device and the ouch flag I did not get how it works reading the documentation. If you could provide more info on it I will try to get it to work.

**Comment by Ironholds** [comment]
Solved by merging #11 - thank you!

**Pull request closed without merging**
