### PR TITLE
update version of uap-core to 23bfabe34b86f29f4840c9dd1ef6129e685581e3

### PR DESCRIPTION
**Pull request by phucnh**
Changes:
- Update sha-1 of submodule uap-core for new useragents
uap-core diff: https://github.com/ua-parser/uap-core/compare/49b141ffe86d5138c332f733d6b2007675bbeb43...23bfabe34b86f29f4840c9dd1ef6129e685581e3
- Add .travis.yml

### CODE REVIEW

**Comment by bpossolo** [comment]
@phucnh have you verified it passes all tests?

**Comment by phucnh** [comment]
@bpossolo 
I have verified the tests passed in my local env.

But don't know how to run the test on travis-ci. Cloud you please let me know how to do it 🙇 

On travis-ci, I got [error:](https://travis-ci.org/ua-parser/uap-java/requests) `Build config file is required via repository settings, but config is empty`

FYI, test result (in my local env)

```
$ mvn test                
[MVNVM] Using maven: 3.5.2
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building User Agent Parser for Java 1.4.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ uap-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to ua_parser
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ uap-java ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ uap-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources to ua_parser
[INFO] Copying 3 resources to ua_parser
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ uap-java ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ uap-java ---
[INFO] Surefire report directory: /Users/a13942/Workspace/uap-java/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ua_parser.OSTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec
Running ua_parser.DeviceTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running ua_parser.ParserTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.233 sec
Running ua_parser.UserAgentTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running ua_parser.CachingParserTest
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 50.013 sec

Results :

Tests run: 35, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2018-10-10T11:47:06+09:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
```

**Comment by phucnh** [comment]
@bpossolo Hi, I have added the `.travis.yml` and have verified all tests are passed. 
PTAL

**Comment by phucnh** [comment]
@bpossolo Hi, cloud you please take another look

**Comment by bpossolo** [comment]
I just updated to latest version of snakeyaml to address a security vulnerability and also updated uap-core to latest.
thank you for submitting

**Pull request closed without merging**
